# -*- coding: utf-8; -*-

#+STARTUP: hidestars

* 氢能源
** 人类的能源发展历程
  - 最早使用的木材，基本上是碳，只含一点点氢
  - 之后是煤炭，两分碳一分氢
  - 发展到石油，两分氢一分碳
  - 再到天然气，四分氢一分碳
  从这个发展过程来看，人类能源的发展基本上是向氢碳比高的方向发展。
** 氢气自然界中不存在
  - 内燃机的效率大概30%
  - 燃料电池的效率可以达到60%
** 氢气的特点
*** 易燃性
  燃烧范围宽，氢气在体积比浓度为4%～75%范围内均可燃烧
*** 泄漏性
  泄漏速率高，泄漏能量低
*** 易扩散性
  常温常压下，氢气的扩散系数为0.61cm2/s，而天然气0.16cm2/s，汽油仅为0.05cm2/s
*** 氢脆现象
  氢气在高于300摄氏度和30MPa时，会对金属产生腐蚀，引起金属的塑性下降，最终诱发裂纹或产生断裂。
* 储氢技术
** 参考
 - 车载高压储氢罐技术集中度高 http://www.jzcx.net/article/954.html
** 相关标准                                   
 - 国际标准化组织已出台了ISO/CD 19881《车用压缩氢气瓶》
 - 我国已经完成能够适用于 35MPa 和 70MPa 的高压储氢瓶的相应标准 GB/T 35544-2017《车用压缩氢气铝合金内胆碳纤维全缠绕气瓶》，于2017 年 1 2 月 29 日发布，2018 年 7 月 1 日开始实施。
** 储气瓶
*** 高压减压阀、进口减压阀、燃料电池供氢减压阀
**** 1）原理介绍
高压氢气瓶阀上的电磁阀打开后，经过流阀到一级、二级减压阀到达燃料电池电堆。加氢则是通过受气头（即加氢口），通过单向阀，将氢气加入瓶中储存。
高度集成的高压氢气供应系统。它具有安装简单、集成度高、便于维护等诸多优点。瓶阀上装有压力传感器监控瓶内压力，及时提醒驾驶员加氢。而且管路中也装有安全阀，当一级减压阀出口压力超泄安全阀设定的安全值 安全阀开启泄压，保证下游管路的压力安全
**** 2)压缩氢气车载供氢系统零部件介绍
为了达到电动汽车要求的续驶里程，整车采用高压氢气，而燃料电池电堆使用氢气压力较低，出于车载氢气使用安全的考虑，压缩氢气车载供氢系统零部件主要有高压氢瓶、瓶阀、受气头、单向阀、过流阀、减压阀、压力传感器、管路等-高压减压阀、进口减压阀、燃料电池供氢减压阀
***** ①氢气瓶：
氢气瓶采用铝内胆，外面用碳纤维缠绕后增加气瓶耐压，从而能够提高压缩氢气量，满足车载储氢诸多要求
***** ②瓶阀：
氢气属于易燃易爆的危险化学品，其使用安全非常重要，因此瓶阀的功能也很重要。该瓶阀上集成了电磁阀、手动截止阀、熔栓阀、温度传感器。瓶阀共有四个进出口，其中一个为PRD口（出现异常情况时候泄气用），其余一个进出口安装高压压力传感器，一个进出口用于车载氢气使用时的通路口，剩下的一个进出口作为备用，可以用堵头封住.
熔栓阀的作用是当瓶周围温度到达该阀的设定温度值时自动熔断，起到打开瓶阀泄压的目的。这些设计充分保证氢气在车上使用时的安全。
***** ③减压阀：
减压阀的作用是使上游入口端的高压气体通过机械方式达到出口端时获得一个稳定的输出压力。一般情况下燃料电池电动汽车上都配备有2个或多个减压阀，通常一级减压阀安装在高压氢气段，气体入口压力即为储氢瓶内气体压力，出口压力可根据不同系统的要求加以设定，通常在1~3MPa之间，二级减压阀作用是将一级减压阀的出口气体通过机械调节方式使系统的终出口压力达到燃料电池的使用要求。通过两级或多级减压，可以使得出口压力更稳定、更安全，同时也更好地满足使用要求
***** ④压力传感器：
燃料电池汽车车载供氢系统上都配备有多个压力传感器，包括高压、中压、低压压力传感器。高压压力传感器：安装在瓶阀端口上，用于实时监测氢瓶内气体压力，并将检测结果传输至仪表，其作用类似于传统车的油表，可以告诉驾驶员储氢瓶中氢气残余量；低压压力传感器：其主要作用是实时监测二级减压阀的出口压力是否稳定，从而达到保护燃料电池系统的作用
***** ⑤过流阀：
过流阀是一种安全保护装置。当过流阀两端压差过大时，该阀可以起到限制气体流量的作用，主要是防止管路有破裂等意外。通常建议该阀的安装位詈是紧邻储氢瓶出口，该阀只起暂时关闭的作用，在压差恢复正常时，其功能又恢复正常，这样就可以很好地保护自身及其他系统零部件-高压减压阀、进口减压阀、燃料电池供氢减压阀
***** ⑥管路：
由于高压氢气这样的特殊环境，系统中使用的气体管路采用不锈钢，耐压等级也是符合相关标准系统中可以根据各段管路系统使用的压力要求不同选择不同壁厚的不锈钢管，对系统到达优化的目的。
** 技术指标
*** 丰田Mirai高压储氢瓶
  - 容积：60L
  - 质量储氢密度：5.7%
  - 储氢 3.8kg， 罐自重42.8kg，+ 加封头、减压阀等配件，66kg
  - 不具备“便携可互换性”
* 加氢站
** 典型构成
*** 制氢系统
*** 压缩系统
*** 储存系统
*** 加注系统
*** 控制系统
** 成本高的核心设备
*** 压缩机
**** 液压活塞式氢气压缩机
   - 操作简单，灵活性大
   - 容易造成氢气的污染和泄漏
   - 散热性较差
**** 隔膜式氢气压缩机
   - 散热性性能好
   - 压力极限可超过100MPa
   - 压缩比大
   - 密封性强
   - 不污染压缩介质
**** 主要生产厂家
   - 国外，美国PDC、英国豪顿、德国Andreas Hofer
   - 国内，中鼎横盛、北京天高、江苏恒久机械、北京京城机电
*** 加注设备 - 氢气加注机
   加氢机是最有可能实现国产化的核心设备
**** 生产厂家
   - 国外，德国林德（Linde）、美国AP公司
   - 国内，厚普股份

*** 储氢罐
**** 三级压力储存
   - 低压：20-30MPa
   - 中压：30-40MPa
   - 高压：40-75MPa
   - 长管托车，一级储气：10-20MPa
**** 生产厂家
   - 国外：美国AP公司，CPI公司
   - 国内：浙江大学，攻克 轻质铝内胆纤维全缠绕，但没有形成量产
** 加氢站成本测算
*** 基本假设如下：
（1） 加氢站日加氢量为 500kg，主要设备包括：压缩机、分压机、加氢机、固定储氢瓶等。安装费包 含在设备费用中；
（2） 加氢站占地 4000 平方米左右；
（3） 压缩机平均日加氢能力 500kg/12h，12.5MPa 氢源压力，运行 12 小时可加 20~40 辆大巴车 （8*140L，单车单次加氢量：12.5~25kg）或 50~100 辆物流车（3*140L，单车单次加氢量：5~10kg） 或 85~100 辆乘用车（单车单次加氢量：5~6kg）；
（4） 氢气压缩 43~45MPa，氢气加注 32~35MPa；
（5） 加氢站每年工作 300 天，80%使用率；
（6） 设备折旧 10 年，土地房屋折旧 30 年（不考虑土地及房屋的残值及未来的增减值影响）；
（7） 加氢站设置员工 5 人，薪资每人 8 万元/年；
（8） 为简化计算，运营管理成本等同于人工成本。
*** 测算结果，投资回收期 3.02年 
由测算结果可知，若加氢站规模为 500kg/d，在加氢站环节增加的氢气成本为 14.17 元/kg。现假设加 氢站原料为天然气制氢，运输方式为长管拖车运输（运输距离 100km），氢气售价 60 元/kg，补贴金额 400 万元，其余假设同上，计算得加氢站的投资回收期为 3.02 年。

* 想法
** 便携可更换式高压储氢罐 
   http://www.doc88.com/p-9522932201779.html
 - 充分利用现有覆盖面光的加油站运行多年的资源
 - 加油站存放一定数量的满氢 便携可更换式高压储氢罐
 - 依靠物流云端大数据计算后统一配送
 - 加油站员工进行换罐技能培训，达到安全熟练掌握服务和空罐回收要求
 - 加油站作为过渡，让加油业务平稳转型